### ISSUE TITLE
Hey ,I like quasar-admin very much ,I wanna translate it to Chinese ,so Can I do it 

### ISSUE THREAD

**Issue by AdorableGhost** [pratik227/quasar-admin#1]
I learnt quasar and liked it ,now  I am looking something like vue-element-admin then I got this ,so ,I am Chinese ,I wanna let more Chinese  know  about  this  admin panel ,so Could I translate it and introduce it to My Chinese friends ...

Waitting for you response .
                                                           Adorable Elliot

**Comment by pratik227** [comment]
Hi @AdorableGhost,

Yes, we can implement internationalization in this template. We can talk on discord (Pratik Patel#9040) for further details if you need some help.

Thanks,
Pratik Patel

**Comment by AdorableGhost** [comment]
OK .. I will add you ,and  most likely I will contact you with email if I have problems ....have a good day ..

**Comment by pratik227** [comment]
Hi, @AdorableGhost  you have completed the translation?

**Comment by pratik227** [comment]
I’m closing this issue because it has been inactive for a few months
