### ISSUE TITLE
Q-Cards

### ISSUE THREAD

**Issue by JasonKramer525** [pratik227/quasar-admin#13]
Is there a list of plugins that you used to make this? I am interested in getting the <card-profile> that you used, but I can't find it anywhere online or in Quasar's docs. I am also interested in others that you used and am wondering where to find them. Thank you!

**Comment by pratik227** [comment]
Hi @JasonKramer525,

It's my own custom components I have build using quasar.

**Comment by JasonKramer525** [comment]
> Hi @JasonKramer525,
> 
> It's my own custom components I have build using quasar.

That's awesome! Is there any way I could use them outside of this project?

**Comment by pratik227** [comment]
Yes you can copy the component and then you can use that in your project.🥳
