### ISSUE TITLE
Blinking window on the bottom when switch to Dashboard page

### ISSUE THREAD

**Issue by Claus1** [pratik227/quasar-admin#23]
Reproducing:
1. Select CRM Dashboard.
2. Select Dashboard.
3. See a blue Blinking window at the bottom.

**Comment by pratik227** [comment]
Hi @Claus1,

I don't see a Blinking window. Can you share a screenshot or video of it?

**Comment by Claus1** [comment]
When switch to Dashboard (my resolution 1920x1080) the block To do list appears on the bottom and disappears in ~0.2 sec. 1 Blink. Open https://quasar-admin-demo.netlify.app/ and reproduce 1-3.

**Comment by pratik227** [comment]
Hi @Claus1,

Thanks for the feedback. I'm unable to reproduce it. But I will check and let you know. If you have fixed it you can send me the pull request.

Thanks,
Pratik Patel
