### ISSUE TITLE
Different margins between blocks(cards).

### ISSUE THREAD

**Issue by Claus1** [pratik227/quasar-admin#25]
![margins](https://user-images.githubusercontent.com/1247062/124087885-a55bf880-da7c-11eb-8858-b8f6f66b7eb5.png)
 w1 != w2
 h3 != h4 != h5

It looks like an issue for me. Is it fixable?

**Comment by pratik227** [comment]
Hi @Claus1,

Ok I will fix it and let you know.

**Comment by pratik227** [comment]
Hi @Claus1,

Fixed the issue please check

Thanks,
Pratik Patel

**Comment by Claus1** [comment]
@pratik227  Excellent! Thanks!
