### ISSUE TITLE
reflash https://next-quasar-admin.netlify.app/Dashboard2  failure

### ISSUE THREAD

**Issue by samsomlan** [pratik227/quasar-admin#41]
Page Not Found
Looks like you've followed a broken link or entered a URL that doesn't exist on this site.

[ Back to our site](https://next-quasar-admin.netlify.app/)

If this is your site, and you weren't expecting a 404 for this path, please visit Netlify's ["page not found" support guide](https://answers.netlify.com/t/support-guide-i-ve-deployed-my-site-but-i-still-see-page-not-found/125?utm_source=404page&utm_campaign=community_tracking) for troubleshooting tips.

**Comment by pratik227** [comment]
Hi @samsomlan,

Fixed it it's just netlify deployment issue.

Thanks,
Pratik Patel

**Comment by samsomlan** [comment]
3ks
