### ISSUE TITLE
Node 18   Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by sonicviz** [pratik227/quasar-admin#49]
If you use node 18 it errors trying to run Quasar dev
If you use node 16 it runs ok. 

So, it needs to be updated to be compatible with later node versions as well as updated for Quasar 2+/Vue3.
Any chance of that happening? Thanks!

(node:27940) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
  Error: error:0308010C:digital envelope routines::unsupported

  - hash:69 new Hash
    node:internal/crypto/hash:69:19

  - node:crypto:133 Object.createHash
    node:crypto:133:10

  - createHash.js:135 module.exports
    [quasar-admin]/[webpack]/lib/util/createHash.js:135:53

  - NormalModule.js:417 NormalModule._initBuildHash
    [quasar-admin]/[webpack]/lib/NormalModule.js:417:16

  - NormalModule.js:471 handleParseError
    [quasar-admin]/[webpack]/lib/NormalModule.js:471:10

  - NormalModule.js:503
    [quasar-admin]/[webpack]/lib/NormalModule.js:503:5

  - NormalModule.js:358
    [quasar-admin]/[webpack]/lib/NormalModule.js:358:12

  - LoaderRunner.js:373
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:373:3

  - LoaderRunner.js:214 iterateNormalLoaders
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:214:10

  - LoaderRunner.js:221 iterateNormalLoaders
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:221:10

E:\Source Control\AI Apps\Quasar Boilerplates\quasar-admin\node_modules\loader-runner\lib\LoaderRunner.js:133
                if(isError) throw e;
                            ^

[  Error: error:0308010C:digital envelope routines::unsupported

  - hash:69 new Hash
    node:internal/crypto/hash:69:19

  - node:crypto:133 Object.createHash
    node:crypto:133:10

  - createHash.js:135 module.exports
    [quasar-admin]/[webpack]/lib/util/createHash.js:135:53

  - NormalModule.js:417 NormalModule._initBuildHash
    [quasar-admin]/[webpack]/lib/NormalModule.js:417:16

  - NormalModule.js:471 handleParseError
    [quasar-admin]/[webpack]/lib/NormalModule.js:471:10

  - NormalModule.js:503
    [quasar-admin]/[webpack]/lib/NormalModule.js:503:5

  - NormalModule.js:358
    [quasar-admin]/[webpack]/lib/NormalModule.js:358:12

  - LoaderRunner.js:373
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:373:3

  - LoaderRunner.js:214 iterateNormalLoaders
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:214:10

  - LoaderRunner.js:221 iterateNormalLoaders
    [quasar-admin]/[loader-runner]/lib/LoaderRunner.js:221:10

] {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.17.1

**Comment by pratik227** [comment]
Hi @sonicviz,

I don't see any issues with node 18.

It's working fine. Make sure you are using the next branch.

Thanks,
Pratik Patel

**Comment by sonicviz** [comment]
>>Make sure you are using the next branch.

Aok, that works, thanks. 

I missed you had the next branch set by default when cloning it.

**Comment by pratik227** [comment]
🚀  

Closing this issue.
