### ISSUE TITLE
Unable to Navigate to Login Page on Click of User ID and Profile Photo

### ISSUE THREAD

**Issue by Yeshajagad** [pratik227/quasar-admin#67]
On the main page of [Quasar Minimalist Design](https://quasar-minimalist-design.netlify.app/), the user is unable to navigate to the login page when clicking on the user ID or profile photo. This issue disrupts the user experience, as the expected action is to be directed to the login page or account-related section.

kindly assign me this issue under Hacktoberfest 2024

**Comment by pratik227** [comment]
It's private repo that's diffrent project @Yeshajagad
